# GitLab CI YML file dedicated for LC environment (Quartz)
#
# Spack must be available
# It would be better to install all Boost versions manually,
# as it causes errors often and could exceed the timelimit of the system.
#
# One might want to change the location of builds directory on LC clusters to avoid consuming the home directory space.
# Type the following command on a LC cluster:
# $ ln -s /usr/workspace/lc-username ~/.gitlab-runner

stages:
  - install
  - build


variables:
  GTEST_COLOR: "1"
  GIT_DEPTH: 0
  SPACK_ARCH_INFO: "arch=linux-rhel7-broadwell"
  GCC_VERSION: "8.1.0"
  METALL_VERSION: "0.5"


install_boost:
  stage: install
  tags:
    - quartz
    - shell
  script:
    - hostname
    - pwd
    - spack install boost@1.74.0
    - spack install boost@1.71.0
    - spack install metall@${METALL_VERSION}
    - spack clean
    - spack find


.build:
  stage: build
  tags:
    - quartz
    - shell
  script:
    - salloc -N1 -ppdebug
    - module load gcc/${GCC_VERSION}
    - spack load metall@${METALL_VERSION} ${SPACK_ARCH_INFO}
    - spack load boost@${BOOST_VERSION} ${SPACK_ARCH_INFO}
    - cd build/gitlab_ci
    - sh ./scripts/${BUILD_SCRIPT}
    - make -j
    - export HAVOQGT_TEST_DIR="/dev/shm/havoqgt_test-${CI_CONCURRENT_ID}-${CI_PIPELINE_IID}"
    - make test


build_with_release_boost1.74.0:
  extends: .build
  variables:
    BUILD_SCRIPT: "do_cmake.sh"
    BOOST_VERSION: "1.74.0"

build_with_debug_boost1.74.0:
  extends: .build
  variables:
    BUILD_SCRIPT: "do_cmake_debug.sh"
    BOOST_VERSION: "1.74.0"

build_with_release_boost1.71.0:
  extends: .build
  variables:
    BUILD_SCRIPT: "do_cmake.sh"
    BOOST_VERSION: "1.71.0"

build_with_debug_boost1.71.0:
  extends: .build
  variables:
    BUILD_SCRIPT: "do_cmake_debug.sh"
    BOOST_VERSION: "1.71.0"